[package]
name = "fc-ctl"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
fclib = { git = "https://github.com/bchalios/fclib.git", features = ["clap"]}
clap = { version = "4.3", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
thiserror = "1"
