name: ci
on:
  pull_request:

  push:
    branches:
    - master

  workflow_dispatch:

jobs:
  # At the moment we just test for style issues and that the build
  # doesn't break.
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build fc-ctl
        run: cargo build --verbose

  clippy:
    name: clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Run clippy
        run: cargo clippy --all --verbose

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all --check

  markdown:
    name: markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
